databases:
  - name: eventia-db
    plan: free
    region: oregon

services:
  - type: web
    name: eventia-backend
    runtime: node
    region: oregon
    rootDir: backend
    buildCommand: npm ci && npx prisma generate && sh scripts/migrate-deploy.sh && node src/scripts/seedAdmin.js && node src/scripts/seed.js
    startCommand: node src/index.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventia-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: AI_SERVICE_URL
        value: https://eventia-ai.onrender.com   # update after first deploy
      - key: NODE_ENV
        value: production
      - key: SEED_DB
        value: false

  - type: web
    name: eventia-ai
    runtime: python
    region: oregon
    rootDir: ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free

  - type: web
    name: eventia-frontend
    runtime: node
    region: oregon
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npx serve dist -l $PORT --single
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://eventia-backend.onrender.com   # update after first deploy
